---
sidebar: sidebar
permalink: concept-aiq-digital-advisor.html
keywords: concepts, active iq digital advisor, ontap
summary: Active IQ Digital Advisor is integrated into the BlueXP UI so that you can optimize the operations, security, and performance of your ONTAP clusters in a single pane of glass.
---

= Optimize your clusters using Digital Advisor
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
https://www.netapp.com/services/support/active-iq/[Digital Advisor^] (formerly Active IQ) is integrated into the BlueXP UI so that you can optimize the operations, security, and performance of your ONTAP clusters in a single pane of glass.

== Features

You can view the overall status of your storage system, high-level information about the wellness of the system, inventory, planning, upgrades, and valuable insights at a watchlist level using Digital Advisor.

* Analyze and optimize the health of your storage systems
* Gain insights regarding all the risks to your storage systems and the actions to mitigate the risks
* Analyze the performance of your storage devices by viewing the graphical format of performance data
* Get details about systems that have exceeded 90% capacity or are nearing 90% capacity
* Get information about the hardware and software that have expired or are near-expiration within the next 6 months
* Upgrade your storage system software, and update your ONTAP firmware using Ansible

== Supported ONTAP systems

Digital Advisor provides information for all the on-premises ONTAP systems and Cloud Volumes ONTAP systems within your NSS account.

== Cost

There's no cost to use this service through BlueXP.

== How Digital Advisor works with BlueXP

Refer to https://docs.netapp.com/us-en/active-iq/digital-advisor-integration-with-bluexp.html[Digital Advisor documentation^] for details.