settings:
  name: On-prem ONTAP clusters
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: On-prem ONTAP cluster docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Discover ONTAP clusters
          url: /task-discovering-ontap.html
    - title: Manage on-prem ONTAP clusters
      entries:
        - title: Manage on-prem ONTAP volumes
          url: /task-provisioning-ontap.html
        - title: Administer using System Manager
          url: /task-administer-advanced-view.html
        - title: Optimize clusters using Digital Advisor
          url: /concept-aiq-digital-advisor.html
        - title: Remove an on-prem ONTAP working environment
          url: /task-remove-on-prem.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: All BlueXP documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: View discovered and undiscovered on-prem clusters
          url: task-discovering-ontap.html#viewing-discovered-and-undiscovered-on-prem-clusters
        - title: Discover ONTAP clusters
          url: task-discovering-ontap.html
        - title: What’s New
          url: whats-new.html
    - title: Manage on-prem ONTAP clusters
      links:
        - title: Create volumes
          url: task-provisioning-ontap.html
        - title: Download new disk and shelf firmware
          url: task-managing-ontap.html#downloading-new-disk-and-shelf-firmware
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: BlueXP blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
