---
sidebar: sidebar
permalink: reference-limitations.html
keywords: limitations, system manager, unsupported features
summary: Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.
---

= Known limitations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.

== Limitations related to ASA r2 systems

* You can discover NetApp ASA r2 systems in BlueXP when using BlueXP in standard mode or restricted mode. Discovery of ASA r2 systems is not supported when using BlueXP in private mode.

* After you discover a NetApp ASA r2 system and open the working environment, you're brought directly to System Manager.
+
No other management options are available with ASA r2 systems. You can't use the Standard view and you can't enable BlueXP services.

https://docs.netapp.com/us-en/asa-r2/index.html[Learn more about ASA r2 systems^]

== Unsupported clusters

On-premises ONTAP clusters that are configured with SAML authentication are not supported with BlueXP.

== System Manager limitations

The following System Manager features are not supported from BlueXP:

* Cluster setup
+
After you set the management IP address and configure the admin password on an on-premises ONTAP cluster, you can discover the cluster in BlueXP.

* Role-based access control (Connector only)
+
Role-based access control from System Manager is not supported when discovering and managing an on-prem ONTAP cluster using a Connector. You are prompted to enter your admin credentials during the discovery process. Those credentials are used for all actions taken from System Manager.
+
With the direct discovery option, you're prompted to log in with your ONTAP credentials each time that you open the working environment.

* BlueXP backup and recovery (Cloud Backup) activation
+ 
The cluster version must be 9.13.1 to enable BlueXP backup and recovery from System Manager.
+
If you did _not_ discover a cluster using a Connector, then you can't use System Manager (advanced view) to enable backup and recovery. However, you can enable backup and recovery on an on-premises cluster directly from BlueXP. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html[Learn how to get started^]
 
* On-demand upgrades
+
On-demand upgrades of firmware and software are not available if the cluster version is ONTAP 9.9.1 or earlier.
+
If you do _not_ have a Connector, you cannot make updates from your local machine, only from a server that can be accessed using BlueXP. 

* Global search

* User interface settings
